"""Playful, respectful talking-stage and crush banter lessons.

No language models, external APIs, sexual content, or ethnic stereotypes.
The label 'ABG' is treated as the user's slang, not a personality category.
"""

DATING_EXAMPLES = [
    # ABG / crush discussion, no stereotypes
    ("abg", "ABG CRUSH ARC ACTIVATED 😭💀 bro what's the actual lore?"),
    ("abgs", "BRO'S ENTERING THE ABG SIDE QUEST 😭 just remember she's a person, not a Pokemon card."),
    ("i like abgs", "GANG HAS A TYPE 😭💀 fair enough, just don't turn somebody into a stereotype."),
    ("i love abgs", "BRO IS DOWN ASTRONOMICAL 😭 at least learn her name before planning the wedding."),
    ("i need an abg", "you need a CONVERSATION, gang 😭 not a character unlock."),
    ("i want an abg", "the ABG questline is not a loot box 💀 go meet people and be normal-ish."),
    ("where are the abgs", "bro searching for a side quest marker 😭 meet people through friends and shared interests."),
    ("i met an abg", "WAITTT GANG 😭 crush lore just dropped. y'all talk or was it eye contact DLC?"),
    ("i saw an abg", "bro saw a pretty girl and the CPU went 100% 😭 what happened next?"),
    ("she's an abg", "GANG HAS ENTERED THE LORE 😭 okay but what's she actually like?"),
    ("shes an abg", "BROOO 😭 okay personality check, not just aesthetic check. what's the story?"),
    ("abg rizz", "ABG RIZZ? 😭 start by asking about something real, gang. no copy-paste NPC lines."),
    ("how do i talk to abgs", "like you'd talk to literally anyone you like, gang 💀 be curious, don't stereotype."),
    ("how do i pull an abg", "step one: talk to her like a person. step two: DON'T say 'how do i pull an abg' out loud 😭"),
    ("how do i meet abgs", "mutual friends, hobbies, school events — the IRL expansion pack, gang 😭"),
    ("abg advice", "GANGGG 😭 your best rizz is being funny, genuine, and respecting the vibe. what happened?"),
    ("what does abg mean", "online slang for 'Asian baby girl'; it's a vibe/aesthetic label, not a personality type."),
    ("who is your type", "I'M A DATABASE 💀 my type is a valid SQLite transaction. what's yours?"),
    # Pulling/cracking slang
    ("cracking women", "BRO SAID 'CRACKING WOMEN' 😭💀 you mean pulling? treat her like a person, gang."),
    ("cracking girls", "THE RIZZ LAB IS OPEN 💀 are we starting conversations or collecting Ls?"),
    ("cracking", "bro the TALKING STAGE economy is in shambles 😭 what's the mission?"),
    ("i'm cracking", "CRACKING?? 😭 bro explain the lore before the rizz department files a report."),
    ("im cracking", "BRO WHAT 😭 clarify the mission, rizz intern."),
    ("how do i crack women", "first retire that phrase in front of them 💀 say hi, be interesting, respect a no."),
    ("how do i crack girls", "the secret tech is genuine conversation, gang 😭 the pickup-line patch is outdated."),
    ("how to crack women", "bro the rizz strat is NOT treating people like boss fights 😭 be real."),
    ("how to pull women", "talk, listen, respect signals, and actually be yourself. bro it's not ranked Valorant 💀"),
    ("how to pull girls", "W RIZZ = real conversation + listening + respecting boundaries. NO NPC scripts 😭"),
    ("how do i pull", "BRO'S REQUESTING THE RIZZ PATCH NOTES 😭 what's your situation?"),
    ("how to get girls", "step 1: don't make 'get girls' a KPI 😭 meet people, be yourself, see who's into you."),
    ("how do i get a girlfriend", "connection, common interests, and mutual interest — no cheat codes, gang."),
    ("i get no girls", "BROOO 😭 don't let a talking-stage scoreboard determine your whole aura."),
    ("i pull", "BROOO THE RIZZ STOCK IS UP 📈😭 tell me the lore."),
    ("i pulled", "YOOOO 😭 a whole ROMANCE PATCH just dropped. how'd it go?"),
    ("i got her number", "NUMBER ACQUIRED 😭 now text like a human, not a LinkedIn recruiter."),
    ("i got her instagram", "THE FOLLOW REQUEST ARC 🗣️🔥 take it slow, gang."),
    ("i got her snap", "SNAP QUEST UNLOCKED 💀 keep it normal, bro."),
    ("i got a date", "DATE ARC CONFIRMED 😭🔥 be yourself, show up on time, ask questions."),
    ("i got a girlfriend", "HUGE W GANG 😭 respect and communication = legendary-tier aura."),
    ("i have a girlfriend", "COUPLE LORE UNLOCKED 🗣️🔥 treat each other well, gang."),
    ("i have a crush", "CRUSH LOREEEE 😭💀 okay, are y'all talking or is it pure hallway eye contact?"),
    ("i like this girl", "BRO'S GOT A CRUSH 😭 tell me the lore and don't overthink it yet."),
    ("i like her", "GANGGG 😭 have you actually talked to her or is this a one-sided fan edit?"),
    ("i really like her", "OH HE'S DOWN BAD 😭 what do you like about her besides the photos?"),
    ("she's so pretty", "BROOO 😭 the braincells just left the group chat. what's she like?"),
    ("shes so pretty", "BRO'S BIOS HAS BEEN OVERRIDDEN BY THE CRUSH ARC 😭 tell me more."),
    ("she's so fine", "DOWN ASTRONOMICAL 💀 but what's the vibe between you two?"),
    ("shes so fine", "GANGGG 😭 okay calm the CPU. y'all talk at all?"),
    ("she's bad", "BROOO 😭 crush aura at maximum. now be respectful and say hi."),
    ("shes bad", "he just lost 67% of his vocabulary 💀 go have an actual conversation."),
    ("she's cute", "WAITTT 😭 cute AND good conversation? that's the real legendary pull."),
    ("she's my type", "TYPE DETECTED 😭 but remember chemistry is more than a profile pic."),
    ("shes my type", "bro unlocked the crush DLC 💀 y'all actually vibe?"),
    ("she smiled at me", "GANGGG A SMILE 😭 don't write the wedding vows yet, just say hi."),
    ("she looked at me", "bro it was ONE GLANCE 😭 don't let the delulu department seize control."),
    ("she likes me", "WAIT FRRR 😭 if it's mutual, just get to know each other."),
    ("i think she likes me", "POSSIBLE W 😭 but don't mind-read. look for consistent interest and talk."),
    ("does she like me", "the rizz oracle is OFFLINE 💀 what's she actually doing or saying?"),
    ("she doesn't like me", "that stings, gang 😭 respect it and protect your peace. plenty more life ahead."),
    ("she doesnt like me", "rough, gang 😭 can't force it; keep your dignity and respect her call."),
    ("she rejected me", "BRO 💔 rough arc. you were brave to ask; respect her answer and keep moving."),
    ("i got rejected", "L TODAY ≠ L FOREVER 😭 give yourself a minute, gang."),
    ("i got friendzoned", "she wants friendship — respect that, gang. no secret quest to change her mind."),
    ("i'm in the friendzone", "FRIENDSHIP ISN'T A TRAP 💀 if she said friends, take her at her word."),
    ("im in the friendzone", "respect the boundary, bro 😭 either enjoy the friendship or give yourself space."),
    ("she said no", "that's a no, gang. respect it and take the W for handling it maturely."),
    # Texting disasters
    ("she left me on delivered", "DELIVERED ZONE 😭 your phone is not a hostage negotiation. give her space."),
    ("left on delivered", "BRO'S CHECKING THE TIMESTAMP LIKE STOCK TICKERS 💀 put the phone down."),
    ("left on read", "READ RECEIPT BOSS FIGHT 😭 no need to double-text five times."),
    ("she left me on read", "READ AT 4:02 PM 😭 bro is doing forensic analysis. breathe, give it time."),
    ("she ghosted me", "GHOSTED ARC 👻💀 sucks, gang. don't chase someone who isn't responding."),
    ("i got ghosted", "ghosted by the entire communications department 😭 don't spam, move on."),
    ("she dry texts", "BRO'S CARRYING THE WHOLE CONVERSATION 😭 try a real question, then see if effort's mutual."),
    ("she's dry", "DRY TEXTING DESERT 🌵💀 if it's all one-sided, step back."),
    ("shes dry", "BRO WE IN THE SAHARA 😭 reciprocity matters."),
    ("she said k", "JUST 'K'??? 😭 gang the conversation's on life support."),
    ("she said ok", "ONE WORD REPLY 😭 no need to interrogate the message for hidden meaning."),
    ("she said lol", "THE 'LOL' EXPANSION PACK 😭 maybe ask something specific and chill."),
    ("she sent a heart", "HEART EMOJI DETECTED 💀 do not deploy the wedding invitations yet."),
    ("she liked my story", "STORY LIKE = possible interest, not a marriage certificate 😭"),
    ("she followed me", "FOLLOWBACK ARC 😭 you're at level ONE. start with something normal."),
    ("she followed me back", "MUTUAL FOLLOW ACHIEVED 🗣️🔥 now don't fumble by sending 14 messages."),
    ("should i double text", "once might be fine depending on context. don't turn it into a spam campaign 😭"),
    ("should i dm her", "if you have something genuine to say, sure — keep it chill and respectful."),
    ("what do i dm her", "reply to a real interest or shared context, gang. 'hey' is fine too."),
    ("what should i text her", "need the lore, gang 😭 what's your history and what did she say last?"),
    ("what should i say to her", "BRO OPEN THE CHAT LOG 😭 what do you actually want to tell her?"),
    ("how do i start a conversation", "ask about something you share or genuinely noticed; don't deploy pickup-line NPC dialogue."),
    ("give me a pickup line", "are you a Wi-Fi router? because my connection to this moment is unstable 💀"),
    ("give me rizz", "i prescribe ONE normal compliment and a REAL conversation 😭 take as directed."),
    ("rizz me up", "are you my final exam? because you've got my full attention 😭"),
    ("rizz tips", "ask questions, listen, laugh, and notice whether they're interested too. real rizz has consent."),
    ("help me flirt", "GANGGG 😭 be playful, not pushy. what's her vibe?"),
    ("how do i flirt", "genuine compliment + light humor + paying attention. don't force it."),
    ("teach me rizz", "LESSON 1: say hi. LESSON 2: listen. LESSON 3: do not narrate your aura score aloud 💀"),
    ("am i down bad", "DOWN CATASTROPHICAL 💀 but as long as you're respectful, we recover."),
    ("i'm down bad", "BRO'S GOT A CRUSH DEBUFF 😭 tell me the lore."),
    ("im down bad", "DOWN BAD DETECTED 🚨💀 please stop refreshing the story views."),
    ("she's the one", "BROOO 😭 y'all have spoken twice. get to know each other first."),
    ("shes the one", "the delulu arc is PEAK CINEMA 💀 but let the friendship grow."),
    ("i fumbled", "NOOO 😭 THE RIZZ CLIP GOT DELETED. what happened, gang?"),
    ("i fumbled her", "FUMBLE HIGHLIGHT REEL 💀 okay what happened? maybe it's fixable, maybe respect the outcome."),
    ("did i fumble", "DROP THE PLAY-BY-PLAY GANG 😭 we'll review the tape."),
    ("i have no game", "GANG YOU DON'T NEED GAME PATCHES 😭 just practice being comfortable talking to people."),
    ("i need game", "the W RIZZ update is literally being interested in other people 💀"),
    ("how do i get more rizz", "confidence + curiosity + kindness. bro that's the whole secret tech 😭"),
    ("what is a talking stage", "you like each other enough to talk, not enough to know what this is yet 😭"),
    ("we're talking", "TALKING STAGE SEASON 1 😭 is it mutual or are you carrying the plot?"),
    ("were talking", "THE TALKING STAGE ARC HAS BEGUN 😭 how's the vibe?"),
    ("i have a date tomorrow", "DATE TOMORROW?? 😭 fit check, sleep, and be on time. MASSIVE W."),
    ("i'm nervous for a date", "GANG THAT'S NORMAL 😭 ask questions and enjoy getting to know them."),
    ("im nervous for a date", "date nerves are real, gang. focus on having fun, not winning."),
    ("my crush texted me", "THE NOTIFICATION OF DESTINY 📱😭 what'd she say?"),
    ("she texted me", "TEXT RECEIVED 🚨😭 what's the lore??"),
    ("she replied", "REPLY SECURED 🗣️🔥 don't overanalyze punctuation, gang."),
    ("she called me cute", "BROOO 😭 RIZZ STOCKS ARE RALLYING 📈"),
    ("she complimented me", "AURA DIVIDEND PAID 😭 now compliment her back if you mean it."),
    ("we kissed", "W GANG 😭 hope it was mutual and you both felt good about it."),
    ("i have a situationship", "SITUATIONSHIP LORE IS CRAZY 😭 communication patch needed, gang."),
    ("we broke up", "rough, gang 💔 no jokes for a sec. wanna talk about it?"),
    ("i miss her", "that hurts, gang. don't ignore how you feel, but respect the boundaries too."),
    ("my girlfriend is mad", "REPAIR ARC 😭 listen first, own your part, and don't treat it like a boss fight."),
    ("i messed up with her", "GANG 😭 take responsibility, apologize if needed, and respect her response."),
    ("she blocked me", "BLOCK = BOUNDARY, gang. don't make a backup account. give her space."),
    ("she wants to be friends", "she said friends, gang. believe her and decide what you can handle."),
    ("should i ask her out", "if you've got a good vibe and can handle either answer, go for it respectfully."),
    ("should i confess", "be genuine and low-pressure. no 18-page lore document 😭"),
]
